### ISSUE TITLE
Questions regarding performance

### ISSUE THREAD

**Issue by N3RDIUM** [Oktosha/ray-tracing#1]
Hey there! I'm building my own ray tracer using a mix of taichi, numba, numpy and cython. Thank you for this amazing implementation of Peter Shirley's rt in one weekend. I wanted to know how much time it takes to render the random spheres example scene using your implementation, and what hardware the benchmark was made on.

**Comment by Oktosha** [comment]
Hi! I added some benchmarking code to the repo in the `runme.ipynb`. For your question, it takes 47 sec to render a 1200x675 image on my M2 macbook air.
